name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 0 * * *

jobs:
  tests:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: "ubuntu-latest"
    name: "Tests | PHP ${{ matrix.php-version }} | Drupal ${{ matrix.drupal }}"
    strategy:
      matrix:
        experimental: [false]
        php-version:
          - "7.3"
          - "7.4"
        drupal:
          - "^8.9"
          - "^9.0"
        include:
          - php-version: "7.2"
            drupal: "~8.9"
            experimental: false
          - php-version: "8.0"
            drupal: "^9.0"
            experimental: true
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, gd, exif, iconv
      - name: "Install dependencies"
        run: "composer update --no-progress --prefer-dist"
      - name: "Downgrade dev dependencies"
        run: "composer require phpunit/phpunit:6.5.14 drush/drush:~9 drupal/core-recommended:${{ matrix.drupal }} drupal/core-dev:${{ matrix.drupal }} --with-all-dependencies"
        if: ${{ matrix.drupal == '^8.9' }}
      - name: "Add phpspec/prophecy-phpunit"
        run: "composer require --dev phpspec/prophecy-phpunit:^2"
        if: ${{ matrix.drupal == '^9.0' }}
      - name: "PHPCS"
        run: "php vendor/bin/phpcs src"
#      - name: "PHPStan"
#        run: "php vendor/bin/phpstan analyze src"
      - name: "PHPUnit"
        run: "php vendor/bin/phpunit --debug"
